# vim: tabstop=2 shiftwidth=2 expandtab
version: '2'

# docker-compose file to launch jenkins_master/ELK stack instead of VM.
# This docker-compose file focus on minimum set for TOAD.
services:
  jenkins_master:
    build:
      context: ./dockerfiles
      dockerfile: centos7_base
    container_name: jenkins_master
    entrypoint: /sbin/init
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./:/opt/toad
      - ./container_data/jenkins/data:/var/lib/jenkins/userContent
      - ./container_data/jenkins/log:/var/log/jenkins
      - ./container_data/jenkins/jobs:/etc/jenkins_jobs
    expose:
      - "8080"

  logstash:
    build:
      context: ./dockerfiles
      dockerfile: centos7_base
    container_name: logstash
    entrypoint: /sbin/init
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./:/opt/toad
      - ./container_data/logstash/config:/etc/logstash/conf.d
      - ./container_data/logstash/log:/var/log/logstash/logstash.log
    expose:
      - "5044"

  elasticsearch:
    build:
      context: ./dockerfiles
      dockerfile: centos7_base
    container_name: elasticsearch
    entrypoint: /sbin/init
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./:/opt/toad
      - ./container_data/elasticsearch/log:/var/log/elasticsearch
      - ./container_data/elasticsearch/data:/var/lib/elasticsearch
      - ./container_data/elasticsearch/config:/etc/elasticsearch
    expose:
      - "9200"

  kibana:
    build:
      context: ./dockerfiles
      dockerfile: centos7_base
    container_name: kibana
    entrypoint: /sbin/init
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./:/opt/toad
      - ./container_data/kibana/config:/opt/kibana/config
    expose:
      - "443"
      - "5601"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.61.122.0/24

