version: '2'

# docker-compose file to launch jenkins_master/ELK stack instead of VM, 
# with dovetail project container from OPNFV.
services:
  jenkins_master:
    build: 
      context: ./dockerfiles 
      dockerfile: centos7_base
    container_name: jenkins_master
    entrypoint: /sbin/init
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./:/opt/toad
      - ./container_data/jenkins/data:/var/lib/jenkins/userContent
      - ./container_data/jenkins/log:/var/log/jenkins
      - ./container_data/jenkins/jobs:/etc/jenkins_jobs
    entrypoint: /sbin/init
    ports:
      - "8080:8080"

  logstash:
    build: 
      context: ./dockerfiles 
      dockerfile: centos7_base
    container_name: logstash
    entrypoint: /sbin/init
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./:/opt/toad
      - ./container_data/logstash/config:/etc/logstash/conf.d
      - ./container_data/logstash/log:/var/log/logstash/logstash.log
    entrypoint: /sbin/init
    ports:
      - "5044:5044"

  elasticsearch:
    build: 
      context: ./dockerfiles 
      dockerfile: centos7_base
    container_name: elasticsearch
    entrypoint: /sbin/init
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./:/opt/toad
      - ./container_data/elasticsearch/log:/var/log/elasticsearch
      - ./container_data/elasticsearch/data:/var/lib/elasticsearch
      - ./container_data/elasticsearch/config:/etc/elasticsearch
    entrypoint: /sbin/init
    ports:
      - "9200:9200"

  kibana:
    build: 
      context: ./dockerfiles 
      dockerfile: centos7_base
    container_name: kibana
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./:/opt/toad
      - ./container_data/kibana/config:/opt/kibana/config
    entrypoint: /sbin/init

  dovetail:
    build: 
      context: ./dockerfiles 
      dockerfile: centos7_dovetail
    container_name: dovetail
    entrypoint: /sbin/init
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./:/opt/toad
    entrypoint: /sbin/init
    ports:
      - "443:443"
      - "5601:5601"
